kitty mac meta and pure power manual merge

diff --git a/support/purepower b/support/purepower
--- a/support/purepower
+++ b/support/purepower
@@ -28,11 +28,11 @@
 #   * No needless color switching. The number of stashes you have in a git repository is always
 #     green. Since its meaning is the same in a clean and in a dirty repository, it doesn't change
 #     color.
+#   * Works with any font.
 #
 #                         LEFT PROMPT
 #
-#   * Your current directory is bright blue when under $HOME and brownish everywhere else.
-#   * A lock icon is shown on the far left if you cannot write to the current directory.
+#   * Your current directory is bright blue when it's writable and brownish when not.
 #   * The prompt symbol on the left is '❮' when vicmd keymap is active and '❯' otherwise. It's green
 #     if the last command has succeeded and red if it has failed.
 #   * Git prompt colors:
@@ -54,13 +54,13 @@
 #
 #                        RIGHT PROMPT
 #
-#   * Current time on the far right.
-#   * Last command execution time (in seconds).
 #   * Error code with an optional signal name of the last command if it failed, in red.
-#   * A gear icon if you have background jobs.
-#   * An unlocked lock icon if you are root.
-#   * If you type `custom_rprompt() { echo 'message' }`, you'll get 'message' shown on the right.
-#     Useful to integrate with your scripts that change some sort of state/environment.
+#   * Last command execution time (in seconds).
+#   * '⇶' if you have background jobs.
+#   * user@host in bright yellow if root, grey otherwise.
+#   * If you type `custom_rprompt() { echo 'message' }` in your terminal, you'll get 'message' shown
+#     on the right. Useful for integration with your scripts that change some sort of
+#     state/environment.
 #
 #                       INSTALLATION
 #
@@ -82,17 +82,22 @@
 #
 #                       CONFIGURATION
 #
-# You can set PURE_POWER_MODE before sourcing ~/.purepower to restrict the range of characters it
-# uses.
+# You can set PURE_POWER_MODE before sourcing ~/.purepower to restrict the range of used characters.
 #
 #   * PURE_POWER_MODE=fancy     use unicode characters in the prompt (default)
-#   * PURE_POWER_MODE=portable
+#   * PURE_POWER_MODE=portable  use only ascii characters in the prompt
 #
 # You can switch mode on the fly by setting PURE_POWER_MODE and executing zsh. Useful when you end
-# up in an environment without a capable font and see gibberish on your screen.
+# up in a prehistoric environment and see gibberish on your screen.
 #
 #   PURE_POWER_MODE=portable exec zsh  # switch to portable mode
 #   PURE_POWER_MODE=fancy    exec zsh  # switch to fancy mode
+#
+# To automatically switch to portable mode when logging in from a terminal that doesn't support
+# unicode, put the following incantation in your ~/.zshrc.
+#
+#   [[ $TERM == xterm* ]] || : ${PURE_POWER_MODE:=portable}
+#   source ~/.purepower
 #
 # To configure what gets shown in the prompt, edit ~/.purepower. See
 # https://github.com/romkatv/powerlevel10k/blob/master/README.md#installation-and-configuration for
@@ -112,6 +117,10 @@
 # environment. Make sure colors work well in every situation. Neighboring segments should always
 # have distinct colors.
 #
+# Try different fonts. Pure Power doesn't use esoteric symbols even in fancy mode and thus doesn't
+# require a patched font. Any monospace font will do, although some are notoriously bad at
+# displaying non-ascii symbols in terminals.
+#
 # If you are using Pure Power with Powerlevel9k rather than Powerlevel10k, you'll need to set
 # PURE_POWER_USE_P10K_EXTENSIONS=0 before sourcing ~/.purepower or you'll see gibberish in your left
 # prompt. This option will turn off vi keymap integration, so your prompt symbol will always be '❯'.
@@ -121,8 +130,9 @@
 #                       ATTRIBUTION
 #
 # Visual design of this configuration borrows heavily from https://github.com/sindresorhus/pure.
-# Recretion of Pure look and feel in Powerlevel10k was inspired by
-# https://github.com/iboyperson/p9k-theme-pastel.
+# Recreation of Pure look and feel in Powerlevel10k was inspired by
+# https://github.com/iboyperson/p9k-theme-pastel. The origin myth is chiseled onto
+# https://www.reddit.com/r/zsh/comments/b45w6v/.
 
 if test -z "${ZSH_VERSION}"; then
   echo "purepower: unsupported shell; try zsh instead" >&2
@@ -133,73 +143,73 @@ fi
 () {
   emulate -L zsh && setopt no_unset pipe_fail
 
-  if (( ARGC )); then
-    echo -E "Usage: source ~/.purepower" >&2
-    return 1
+  # `$(_pp_c x y`) evaluates to `y` if the terminal supports >= 256 colors and to `x` otherwise.
+  zmodload zsh/terminfo
+  if (( terminfo[colors] >= 256 )); then
+    function _pp_c() { print -nr -- $2 }
+  else
+    function _pp_c() { print -nr -- $1 }
+    typeset -g POWERLEVEL9K_IGNORE_TERM_COLORS=true
   fi
 
-  local mode=${PURE_POWER_MODE:-portable}
-  case $mode in
-    fancy)
-      local vi_insert=$'\u276F'
-      local vi_cmd=$'\u276E'
-      local lock=$'\uF023'
-      local incoming=$'\u21E3'
-      local outgoing=$'\u21E1'
-      local root=$'\uF09C'
-      local jobs=$'\uF013'
-      ;;
-    *)
-      if [[ $mode != portable ]]; then
-        echo -En "purepower: invalid mode: ${(qq)mode}; " >&2
-        echo -E  "valid options are 'fancy' and 'portable'; falling back to 'portable'" >&2
-      fi
-      local vi_insert='»'
-      local vi_cmd='«'
-      local lock='X'
-      local incoming='↓'
-      local outgoing='↑'
-      local root='#'
-      local jobs='%%'
-      ;;
-  esac
+  # `$(_pp_s x y`) evaluates to `x` in portable mode and to `y` in fancy mode.
+  if [[ ${PURE_POWER_MODE:-fancy} == fancy ]]; then
+    function _pp_s() { print -nr -- $2 }
+  else
+    if [[ $PURE_POWER_MODE != portable ]]; then
+      echo -En "purepower: invalid mode: ${(qq)PURE_POWER_MODE}; " >&2
+      echo -E  "valid options are 'fancy' and 'portable'; falling back to 'portable'" >&2
+    fi
+    function _pp_s() { print -nr -- $1 }
+  fi
 
   typeset -ga POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
-      dir_writable dir context vcs)
+      dir context vcs)
 
   typeset -ga POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
-      status command_execution_time root_indicator background_jobs custom_rprompt time)
+      status command_execution_time background_jobs custom_rprompt)
+
+  local ins=$(_pp_s '>' '❯')
+  local cmd=$(_pp_s '<' '❮')
+  if (( ${PURE_POWER_USE_P10K_EXTENSIONS:-1} )); then
+    local p="\${\${\${KEYMAP:-0}:#vicmd}:+${${ins//\\/\\\\}//\}/\\\}}}"
+    p+="\${\${\$((!\${#\${KEYMAP:-0}:#vicmd})):#0}:+${${cmd//\\/\\\\}//\}/\\\}}}"
+  else
+    p=$ins
+  fi
+  local ok="%F{$(_pp_c 002 076)}${p}%f"
+  local err="%F{$(_pp_c 001 196)}${p}%f"
 
   if (( ${PURE_POWER_USE_P10K_EXTENSIONS:-1} )); then
-    local p="\${\${\${KEYMAP:-0}:#vicmd}:+${${vi_insert//\\/\\\\}//\}/\\\}}}"
-    p+="\${\${\$((!\${#\${KEYMAP:-0}:#vicmd})):#0}:+${${vi_cmd//\\/\\\\}//\}/\\\}}}"
+    typeset -g ZLE_RPROMPT_INDENT=0
+    typeset -g POWERLEVEL9K_SHOW_RULER=true
+    typeset -g POWERLEVEL9K_RULER_CHAR=$(_pp_s '-' '─')
+    typeset -g POWERLEVEL9K_RULER_BACKGROUND=none
+    typeset -g POWERLEVEL9K_RULER_FOREGROUND=$(_pp_c 005 237)
   else
-    p=$vi_insert
+    typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
   fi
 
-  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?.%F{002}${p}%f.%F{009}${p}%f) "
-  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=$'\n'
   typeset -g POWERLEVEL9K_PROMPT_ON_NEWLINE=true
   typeset -g POWERLEVEL9K_RPROMPT_ON_NEWLINE=false
+  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=
+  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="%(?.$ok.$err) "
 
-  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=' '
+  typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=
   typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=' '
   typeset -g POWERLEVEL9K_WHITESPACE_BETWEEN_{LEFT,RIGHT}_SEGMENTS=
 
-  typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_BACKGROUND=none
-  typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_VISUAL_IDENTIFIER_COLOR=003
-  typeset -g POWERLEVEL9K_LOCK_ICON=''
-
-  typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT}_BACKGROUND=none
-  typeset -g POWERLEVEL9K_DIR_{ETC,DEFAULT}_FOREGROUND=209
-  typeset -g POWERLEVEL9K_DIR_{HOME,HOME_SUBFOLDER}_FOREGROUND=081
-  typeset -g POWERLEVEL9K_{ETC,FOLDER,HOME,HOME_SUB}_ICON=
+  typeset -g POWERLEVEL9K_DIR_SHOW_WRITABLE=true
+  typeset -g POWERLEVEL9K_DIR_{ETC,HOME,HOME_SUBFOLDER,DEFAULT,NOT_WRITABLE}_BACKGROUND=none
+  typeset -g POWERLEVEL9K_DIR_NOT_WRITABLE_FOREGROUND=$(_pp_c 003 209)
+  typeset -g POWERLEVEL9K_DIR_{HOME,HOME_SUBFOLDER,ETC,DEFAULT}_FOREGROUND=$(_pp_c 004 081)
+  typeset -g POWERLEVEL9K_{ETC,FOLDER,HOME,HOME_SUB,LOCK}_ICON=
 
   typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED,LOADING}_BACKGROUND=none
-  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=244
-  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=014
-  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=011
-  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=244
+  typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND=$(_pp_c 002 076)
+  typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND=$(_pp_c 006 014)
+  typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND=$(_pp_c 003 011)
+  typeset -g POWERLEVEL9K_VCS_LOADING_FOREGROUND=$(_pp_c 005 244)
   typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNTRACKEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND
   typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_UNSTAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
   typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_STAGEDFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_MODIFIED_FOREGROUND
@@ -209,48 +219,43 @@ fi
   typeset -g POWERLEVEL9K_VCS_{CLEAN,UNTRACKED,MODIFIED}_ACTIONFORMAT_FOREGROUND=001
   typeset -g POWERLEVEL9K_VCS_LOADING_ACTIONFORMAT_FOREGROUND=$POWERLEVEL9K_VCS_LOADING_FOREGROUND
   typeset -g POWERLEVEL9K_VCS_{GIT,GIT_GITHUB,GIT_BITBUCKET,GIT_GITLAB,BRANCH}_ICON=
-  typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'\b|'
+  typeset -g POWERLEVEL9K_VCS_REMOTE_BRANCH_ICON=$'%{\b|%}'
   typeset -g POWERLEVEL9K_VCS_COMMIT_ICON='@'
-  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON=$'\b?'
-  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON=$'\b*'
-  typeset -g POWERLEVEL9K_VCS_STAGED_ICON=$'\b+'
-  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$incoming
-  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$outgoing
+  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
+  typeset -g POWERLEVEL9K_VCS_UNSTAGED_ICON='!'
+  typeset -g POWERLEVEL9K_VCS_STAGED_ICON='+'
+  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON=$(_pp_s '<' '⇣')
+  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON=$(_pp_s '>' '⇡')
   typeset -g POWERLEVEL9K_VCS_STASH_ICON='*'
-  typeset -g POWERLEVEL9K_VCS_TAG_ICON='#'
+  typeset -g POWERLEVEL9K_VCS_TAG_ICON=$'%{\b#%}'
+  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED}_MAX_NUM=99
 
-  typeset -g POWERLEVEL9K_ROOT_INDICATOR_BACKGROUND=none
-  typeset -g POWERLEVEL9K_ROOT_ICON=$root
+  typeset -g POWERLEVEL9K_STATUS_OK=false
+  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
+  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=$(_pp_c 001 009)
+  typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=
+
+  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
+  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=none
+  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=$(_pp_c 005 101)
+  typeset -g POWERLEVEL9K_EXECUTION_TIME_ICON=
 
   typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VERBOSE=false
   typeset -g POWERLEVEL9K_BACKGROUND_JOBS_BACKGROUND=none
   typeset -g POWERLEVEL9K_BACKGROUND_JOBS_VISUAL_IDENTIFIER_COLOR=002
-  # typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON=$jobs
-  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON='%%'
-
-  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=0
-  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=none
-  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=101
-  typeset -g POWERLEVEL9K_EXECUTION_TIME_ICON=
-
-  typeset -g POWERLEVEL9K_TIME_BACKGROUND=none
-  typeset -g POWERLEVEL9K_TIME_FOREGROUND=244
-  typeset -g POWERLEVEL9K_TIME_ICON=
-
-  typeset -g POWERLEVEL9K_STATUS_OK=false
-  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=none
-  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=009
-  typeset -g POWERLEVEL9K_CARRIAGE_RETURN_ICON=
+  typeset -g POWERLEVEL9K_BACKGROUND_JOBS_ICON=$(_pp_s '%%' '⇶')
 
   typeset -g POWERLEVEL9K_CUSTOM_RPROMPT=custom_rprompt
   typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_BACKGROUND=none
-  typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_FOREGROUND=012
+  typeset -g POWERLEVEL9K_CUSTOM_RPROMPT_FOREGROUND=$(_pp_c 004 012)
 
   typeset -g DEFAULT_USER=$USER
-  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=244
-  typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=214
-  typeset -g POWERLEVEL9K_CONTEXT_SUDO_FOREGROUND=009
-  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=009
+  typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,ROOT,REMOTE_SUDO,REMOTE,SUDO}_BACKGROUND=none
+  typeset -g POWERLEVEL9K_CONTEXT_DEFAULT_FOREGROUND=$(_pp_c 007 244)
+  typeset -g POWERLEVEL9K_CONTEXT_REMOTE_FOREGROUND=$(_pp_c 007 005)
+  typeset -g POWERLEVEL9K_CONTEXT_{REMOTE_SUDO,SUDO}_FOREGROUND=$(_pp_c 007 009)
+  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=$(_pp_c 003 011)
 
+  unfunction _pp_c _pp_s
   function custom_rprompt() {}  # redefine this to show stuff in custom_rprompt segment
 } "$@"
