timesort ls by default

diff --git a/link/functions b/link/functions
--- a/link/functions
+++ b/link/functions
@@ -585,3 +585,18 @@ gremote ()
     echo "Opening $repoUrl"
     open $repoUrl
 }
+
+get_probe() {
+  serial=$(cyme --vidpid=0x1d50:0x6018 --blocks serial --no-color)
+
+  if [ -z "$serial" ]; then
+    echo "Could not find Black Magic Probe on USB"
+    exit 1
+  fi
+
+  if [ "$(uname)" == "Darwin" ]; then
+    probe="$(find /dev/cu.usbmodem"$serial"* | head -n 1)"
+  else
+    probe=/dev/ttyACM0
+  fi
+}
