auto detect BMP

diff --git a/support/scripts/bin/bmp-flash b/support/scripts/bin/bmp-flash
--- a/support/scripts/bin/bmp-flash
+++ b/support/scripts/bin/bmp-flash
@@ -1,26 +1,39 @@
 #!/bin/bash
 # Flash a binary to the Black Magic Probe
 # Usage: bmp-flash <binary>
+set -e
 
-device=/dev/ttyBmpGdb
+probe=/dev/ttyBmpGdb
 
-if [ ! -e $device ]; then
-  if [ "$(uname)" == "Darwin" ]; then
-    device=$(find /dev/cu.usbmodemB* | head -n 1)
-  else
-    device=/dev/ttyACM0
+get_probe() {
+  serial=$(cyme --vidpid=0x1d50:0x6018 --blocks serial --no-color)
+
+  echo "Found BMP $serial"
+  if [ -z "$serial" ]; then
+    echo "Could not find Black Magic Probe 0x1d50:0x6018!"
+    exit 1
   fi
+
+  if [ "$(uname)" == "Darwin" ]; then
+    probe="$(find /dev/cu.usbmodem"$serial"* | head -n 1)"
+  else
+    probe="$(find /dev/tty"$serial"* | head -n 1)"
+  fi
+}
+
+if [ ! -e "$probe" ]; then
+  get_probe
 fi
 
-if [ ! -e $device ]; then
+if [ ! -e "$probe" ]; then
   echo "Black Magic Probe not found!"
   exit 1
 fi
 
 if [ ! -e "${1}" ]; then
-  echo "${1} not found!"
+  echo "File ${1} not found!"
   exit 1
 fi
 
-echo "Flashing ${1} to ${device}..."
-arm-none-eabi-gdb -nx --batch -ex "target extended-remote $device" -x "${HOME}"/dotfiles/support/scripts/embedded/bmp_flash.scr "${1}"
+echo "Flashing ${1} to ${probe}..."
+arm-none-eabi-gdb -nx --batch -ex "target extended-remote $probe" -x "${HOME}"/dotfiles/support/scripts/embedded/bmp_flash.scr "${1}"
diff --git a/support/scripts/bin/bmp-tpwr b/support/scripts/bin/bmp-tpwr
--- a/support/scripts/bin/bmp-tpwr
+++ b/support/scripts/bin/bmp-tpwr
@@ -4,19 +4,32 @@
 # Usage: bmp-tpwr [enable|disable]
 
 option=${1:-enable}
-device=/dev/ttyBmpGdb
 
-if [ ! -e $device ]; then
-  if [ "$(uname)" == "Darwin" ]; then
-    device=$(find /dev/cu.usbmodem* | head -n 1)
-  else
-    device=/dev/ttyACM0
+probe=/dev/ttyBmpGdb
+
+get_probe() {
+  serial=$(cyme --vidpid=0x1d50:0x6018 --blocks serial --no-color)
+
+  echo "Found BMP $serial"
+  if [ -z "$serial" ]; then
+    echo "Could not find Black Magic Probe 0x1d50:0x6018!"
+    exit 1
   fi
+
+  if [ "$(uname)" == "Darwin" ]; then
+    probe="$(find /dev/cu.usbmodem"$serial"* | head -n 1)"
+  else
+    probe="$(find /dev/tty"$serial"* | head -n 1)"
+  fi
+}
+
+if [ ! -e "$probe" ]; then
+  get_probe
 fi
 
-if [ ! -e $device ]; then
+if [ ! -e "$probe" ]; then
   echo "Black Magic Probe not found"
   exit 1
 fi
 
-arm-none-eabi-gdb -ex "target extended-remote $device" -ex "monitor tpwr $option" -ex "quit"
+arm-none-eabi-gdb -ex "target extended-remote $probe" -ex "monitor tpwr $option" -ex "quit"
